"""
MCP Token Generation Service

This service creates tokens specifically for MCP (Model Context Protocol) requests.
These tokens are generated by the frontend after successful Supabase authentication
and are used to authenticate MCP operations.
"""

import logging
import secrets
import hashlib
import time
from datetime import datetime, timedelta, timezone
from typing import Optional, Dict, Any
from dataclasses import dataclass

from ..supabase_client import TokenInfo
from ..infrastructure.supabase_auth import SupabaseAuthService

logger = logging.getLogger(__name__)


@dataclass
class MCPToken:
    """MCP Token information"""
    token: str
    user_id: str
    created_at: datetime
    expires_at: Optional[datetime]
    source_type: str  # 'supabase' or 'local'
    metadata: Dict[str, Any]


class MCPTokenService:
    """
    Service for generating and managing MCP tokens.
    
    MCP tokens are short-lived tokens generated from authenticated
    Supabase sessions for use with MCP operations.
    """
    
    def __init__(self):
        self.supabase_auth = SupabaseAuthService()
        self._token_cache: Dict[str, MCPToken] = {}
        self._user_tokens: Dict[str, str] = {}  # user_id -> token mapping
        logger.info("MCP Token Service initialized")
    
    async def generate_mcp_token_from_supabase(
        self,
        supabase_token: str,
        expires_in_hours: int = 24
    ) -> MCPToken:
        """
        Generate an MCP token from a valid Supabase token.
        
        Args:
            supabase_token: Valid Supabase JWT token
            expires_in_hours: Token expiration in hours (default: 24)
            
        Returns:
            Generated MCP token
            
        Raises:
            ValueError: If Supabase token is invalid
        """
        # Verify the Supabase token first
        result = await self.supabase_auth.verify_token(supabase_token)
        
        if not result.success or not result.user:
            raise ValueError("Invalid Supabase token")
        
        user_id = result.user.id if hasattr(result.user, 'id') else result.user.get('id')
        email = result.user.email if hasattr(result.user, 'email') else result.user.get('email')
        
        if not user_id:
            raise ValueError("Unable to extract user ID from Supabase token")
        
        # Generate MCP token
        mcp_token = self._generate_secure_token(user_id)
        
        # Create expiration time
        expires_at = datetime.now(timezone.utc) + timedelta(hours=expires_in_hours)
        
        # Create MCP token object
        mcp_token_obj = MCPToken(
            token=mcp_token,
            user_id=user_id,
            created_at=datetime.now(timezone.utc),
            expires_at=expires_at,
            source_type='supabase',
            metadata={
                'email': email,
                'source_token_type': 'supabase_jwt',
                'generated_at': int(time.time())
            }
        )
        
        # Cache the token
        self._token_cache[mcp_token] = mcp_token_obj
        
        # Update user -> token mapping (invalidate previous token)
        old_token = self._user_tokens.get(user_id)
        if old_token and old_token in self._token_cache:
            del self._token_cache[old_token]
        
        self._user_tokens[user_id] = mcp_token
        
        logger.info(f"Generated MCP token for user {email} (expires in {expires_in_hours}h)")
        
        return mcp_token_obj
    
    async def generate_mcp_token_from_user_id(
        self,
        user_id: str,
        email: str,
        expires_in_hours: int = 24,
        metadata: Optional[Dict[str, Any]] = None
    ) -> MCPToken:
        """
        Generate an MCP token directly from user ID (for authenticated users).
        
        Args:
            user_id: User ID
            email: User email
            expires_in_hours: Token expiration in hours (default: 24)
            metadata: Additional metadata for the token
            
        Returns:
            Generated MCP token
        """
        # Generate MCP token
        mcp_token = self._generate_secure_token(user_id)
        
        # Create expiration time
        expires_at = datetime.now(timezone.utc) + timedelta(hours=expires_in_hours)
        
        # Prepare metadata
        token_metadata = {
            'email': email,
            'source_token_type': 'user_authenticated',
            'generated_at': int(time.time())
        }
        if metadata:
            token_metadata.update(metadata)
        
        # Create MCP token object
        mcp_token_obj = MCPToken(
            token=mcp_token,
            user_id=user_id,
            created_at=datetime.now(timezone.utc),
            expires_at=expires_at,
            source_type='user_authenticated',
            metadata=token_metadata
        )
        
        # Cache the token
        self._token_cache[mcp_token] = mcp_token_obj
        
        # Update user -> token mapping (invalidate previous token)
        old_token = self._user_tokens.get(user_id)
        if old_token and old_token in self._token_cache:
            del self._token_cache[old_token]
        
        self._user_tokens[user_id] = mcp_token
        
        logger.info(f"Generated MCP token for user {email} (expires in {expires_in_hours}h)")
        
        return mcp_token_obj
    
    async def validate_mcp_token(self, token: str) -> Optional[MCPToken]:
        """
        Validate an MCP token.
        
        Args:
            token: MCP token to validate
            
        Returns:
            MCPToken if valid, None otherwise
        """
        # Check cache first
        if token in self._token_cache:
            mcp_token = self._token_cache[token]
            
            # Check expiration
            if mcp_token.expires_at and datetime.now(timezone.utc) > mcp_token.expires_at:
                # Token expired, remove from cache
                self._remove_token_from_cache(token)
                logger.debug(f"MCP token expired for user {mcp_token.user_id}")
                return None
            
            logger.debug(f"MCP token validated for user {mcp_token.user_id}")
            return mcp_token
        
        logger.debug("MCP token not found in cache")
        return None
    
    async def revoke_mcp_token(self, token: str) -> bool:
        """
        Revoke an MCP token.
        
        Args:
            token: Token to revoke
            
        Returns:
            True if revoked successfully
        """
        if token in self._token_cache:
            mcp_token = self._token_cache[token]
            self._remove_token_from_cache(token)
            logger.info(f"Revoked MCP token for user {mcp_token.user_id}")
            return True
        
        return False
    
    async def revoke_user_tokens(self, user_id: str) -> bool:
        """
        Revoke all MCP tokens for a specific user.
        
        Args:
            user_id: User ID
            
        Returns:
            True if any tokens were revoked
        """
        revoked = False
        
        # Find and remove user's token
        if user_id in self._user_tokens:
            token = self._user_tokens[user_id]
            if token in self._token_cache:
                del self._token_cache[token]
                revoked = True
            del self._user_tokens[user_id]
        
        # Also check cache for any orphaned tokens
        tokens_to_remove = []
        for token, mcp_token in self._token_cache.items():
            if mcp_token.user_id == user_id:
                tokens_to_remove.append(token)
        
        for token in tokens_to_remove:
            del self._token_cache[token]
            revoked = True
        
        if revoked:
            logger.info(f"Revoked all MCP tokens for user {user_id}")
        
        return revoked
    
    def get_token_stats(self) -> Dict[str, Any]:
        """
        Get statistics about current tokens.
        
        Returns:
            Token statistics
        """
        now = datetime.now(timezone.utc)
        active_tokens = 0
        expired_tokens = 0
        
        for mcp_token in self._token_cache.values():
            if mcp_token.expires_at and now > mcp_token.expires_at:
                expired_tokens += 1
            else:
                active_tokens += 1
        
        return {
            'total_tokens': len(self._token_cache),
            'active_tokens': active_tokens,
            'expired_tokens': expired_tokens,
            'unique_users': len(self._user_tokens)
        }
    
    async def cleanup_expired_tokens(self) -> int:
        """
        Clean up expired tokens from cache.
        
        Returns:
            Number of tokens cleaned up
        """
        now = datetime.now(timezone.utc)
        expired_tokens = []
        
        for token, mcp_token in self._token_cache.items():
            if mcp_token.expires_at and now > mcp_token.expires_at:
                expired_tokens.append(token)
        
        for token in expired_tokens:
            self._remove_token_from_cache(token)
        
        if expired_tokens:
            logger.info(f"Cleaned up {len(expired_tokens)} expired MCP tokens")
        
        return len(expired_tokens)
    
    def _generate_secure_token(self, user_id: str) -> str:
        """
        Generate a secure MCP token.
        
        Args:
            user_id: User ID to include in token generation
            
        Returns:
            Secure token string
        """
        # Generate random bytes
        random_bytes = secrets.token_bytes(32)
        
        # Create token content
        token_content = f"{user_id}:{int(time.time())}:{random_bytes.hex()}"
        
        # Hash the content for security
        token_hash = hashlib.sha256(token_content.encode()).hexdigest()
        
        # Create final token with prefix
        return f"mcp_{token_hash[:48]}"
    
    def _remove_token_from_cache(self, token: str) -> None:
        """
        Remove token from all caches.
        
        Args:
            token: Token to remove
        """
        if token in self._token_cache:
            mcp_token = self._token_cache[token]
            
            # Remove from token cache
            del self._token_cache[token]
            
            # Remove from user mapping if it matches
            if (mcp_token.user_id in self._user_tokens and 
                self._user_tokens[mcp_token.user_id] == token):
                del self._user_tokens[mcp_token.user_id]


# Global service instance
mcp_token_service = MCPTokenService()